### ISSUE TITLE
Attempting to use Sleep Animation fails...

### ISSUE THREAD

**Issue by Twilight13** [Mirreski/RandomSK#18]
When I use this skript:

command /sleep:
    trigger:
        make player sleep at block at location of player
        wait 2 seconds
        wake up the player

the player just twitches slightly, with no sleeping animation, and I get this in the server console:

[18:49:15 WARN](java.lang.NullPointerException): java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/EntityPlayer
[18:49:15 WARN](java.lang.NullPointerException):        at java.lang.Class.forName0(Native Method)
[18:49:15 WARN](java.lang.NullPointerException):        at java.lang.Class.forName(Unknown Source)
[18:49:15 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.reflection.helpers.HelperManager.fetchClass(HelperManager.java:226)
[18:49:15 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.reflection.helpers.HelperManager.fetchField(HelperManager.java:277)
[18:49:15 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.reflection.helpers.HelperManager.getFromField(HelperManager.java:114
)
[18:49:15 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.reflection.helpers.ClassHelper.getFromField(ClassHelper.java:79)
[18:49:15 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.reflection.helpers.ObjectHelper.getFromField(ObjectHelper.java:34)
[18:49:15 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.CommonUtils.getPlayerConnection(CommonUtils.java:28)
[18:49:15 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.nms.packets.RawPacket.sendRawPacket(RawPacket.java:49)
[18:49:15 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.nms.packets.PacketSend.sleepAnimation(PacketSend.java:74)
[18:49:15 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.SleepHandler.sleep(SleepHandler.java:36)
[18:49:15 WARN](java.lang.NullPointerException):        at me.mirreski.random.skript.features.packet.EffSleep.execute(EffSleep.java:32)
[18:49:15 WARN](java.lang.NullPointerException):        at ch.njol.skript.lang.Effect.run(Effect.java:50)
[18:49:15 WARN](java.lang.NullPointerException):        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63)
[18:49:15 WARN](java.lang.NullPointerException):        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91)
[18:49:15 WARN](java.lang.NullPointerException):        at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[18:49:15 WARN](java.lang.NullPointerException):        at ch.njol.skript.command.ScriptCommand$1.call(ScriptCommand.java:220)
[18:49:15 WARN](java.lang.NullPointerException):        at ch.njol.skript.command.ScriptCommand$1.call(ScriptCommand.java:1)
[18:49:15 WARN](java.lang.NullPointerException):        at ch.njol.skript.util.Task.callSync(Task.java:139)
[18:49:15 WARN](java.lang.NullPointerException):        at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:193)
[18:49:15 WARN](java.lang.NullPointerException):        at ch.njol.skript.command.Commands.handleCommand(Commands.java:260)
[18:49:15 WARN](java.lang.NullPointerException):        at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:155)
[18:49:15 WARN](java.lang.NullPointerException):        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:49:15 WARN](java.lang.NullPointerException):        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[18:49:15 WARN](java.lang.NullPointerException):        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:49:15 WARN](java.lang.NullPointerException):        at java.lang.reflect.Method.invoke(Unknown Source)
[18:49:15 WARN](java.lang.NullPointerException):        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334)
[18:49:15 WARN](java.lang.NullPointerException):        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[18:49:15 WARN](java.lang.NullPointerException):        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507)
[18:49:15 WARN](java.lang.NullPointerException):        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492)
[18:49:15 WARN](java.lang.NullPointerException):        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1325)
[18:49:15 WARN](java.lang.NullPointerException):        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1129)
[18:49:15 WARN](java.lang.NullPointerException):        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.jav
a:38)
[18:49:15 WARN](java.lang.NullPointerException):        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.jav
a:53)
[18:49:15 WARN](java.lang.NullPointerException):        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
[18:49:15 WARN](java.lang.NullPointerException):        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
[18:49:15 WARN](java.lang.NullPointerException):        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980)
[18:49:15 WARN](java.lang.NullPointerException):        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
[18:49:15 WARN](java.lang.NullPointerException):        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
[18:49:15 WARN](java.lang.NullPointerException):        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
[18:49:15 WARN](java.lang.NullPointerException):        at java.lang.Thread.run(Unknown Source)

[18:49:15 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.reflection.helpers.HelperManager.getFromField(HelperManager.java:115
)
[18:49:15 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.reflection.helpers.ClassHelper.getFromField(ClassHelper.java:79)
[18:49:15 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.reflection.helpers.ObjectHelper.getFromField(ObjectHelper.java:34)
[18:49:15 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.CommonUtils.getPlayerConnection(CommonUtils.java:28)
[18:49:15 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.nms.packets.RawPacket.sendRawPacket(RawPacket.java:49)
[18:49:15 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.nms.packets.PacketSend.sleepAnimation(PacketSend.java:74)
[18:49:15 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.SleepHandler.sleep(SleepHandler.java:36)
[18:49:15 WARN](java.lang.NullPointerException):        at me.mirreski.random.skript.features.packet.EffSleep.execute(EffSleep.java:32)
[18:49:15 WARN](java.lang.NullPointerException):        at ch.njol.skript.lang.Effect.run(Effect.java:50)
[18:49:15 WARN](java.lang.NullPointerException):        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63)
[18:49:15 WARN](java.lang.NullPointerException):        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91)
[18:49:15 WARN](java.lang.NullPointerException):        at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[18:49:15 WARN](java.lang.NullPointerException):        at ch.njol.skript.command.ScriptCommand$1.call(ScriptCommand.java:220)
[18:49:15 WARN](java.lang.NullPointerException):        at ch.njol.skript.command.ScriptCommand$1.call(ScriptCommand.java:1)
[18:49:15 WARN](java.lang.NullPointerException):        at ch.njol.skript.util.Task.callSync(Task.java:139)
[18:49:15 WARN](java.lang.NullPointerException):        at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:193)
[18:49:15 WARN](java.lang.NullPointerException):        at ch.njol.skript.command.Commands.handleCommand(Commands.java:260)
[18:49:15 WARN](java.lang.NullPointerException):        at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:155)
[18:49:15 WARN](java.lang.NullPointerException):        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:49:15 WARN](java.lang.NullPointerException):        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[18:49:15 WARN](java.lang.NullPointerException):        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:49:15 WARN](java.lang.NullPointerException):        at java.lang.reflect.Method.invoke(Unknown Source)
[18:49:15 WARN](java.lang.NullPointerException):        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334)
[18:49:15 WARN](java.lang.NullPointerException):        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[18:49:15 WARN](java.lang.NullPointerException):        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507)
[18:49:15 WARN](java.lang.NullPointerException):        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492)
[18:49:15 WARN](java.lang.NullPointerException):        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1325)
[18:49:15 WARN](java.lang.NullPointerException):        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1129)
[18:49:15 WARN](java.lang.NullPointerException):        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.jav
a:38)
[18:49:15 WARN](java.lang.NullPointerException):        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.jav
a:53)
[18:49:15 WARN](java.lang.NullPointerException):        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
[18:49:15 WARN](java.lang.NullPointerException):        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
[18:49:15 WARN](java.lang.NullPointerException):        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980)
[18:49:15 WARN](java.lang.NullPointerException):        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
[18:49:15 WARN](java.lang.NullPointerException):        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
[18:49:15 WARN](java.lang.NullPointerException):        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
[18:49:15 WARN](java.lang.NullPointerException):        at java.lang.Thread.run(Unknown Source)
[18:49:17 WARN](java.lang.NullPointerException): java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/EntityPlayer
[18:49:17 WARN](java.lang.NullPointerException):        at java.lang.Class.forName0(Native Method)
[18:49:17 WARN](java.lang.NullPointerException):        at java.lang.Class.forName(Unknown Source)
[18:49:17 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.reflection.helpers.HelperManager.fetchClass(HelperManager.java:226)
[18:49:17 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.reflection.helpers.HelperManager.fetchField(HelperManager.java:277)
[18:49:17 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.reflection.helpers.HelperManager.getFromField(HelperManager.java:114
)
[18:49:17 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.reflection.helpers.ClassHelper.getFromField(ClassHelper.java:79)
[18:49:17 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.reflection.helpers.ObjectHelper.getFromField(ObjectHelper.java:34)
[18:49:17 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.CommonUtils.getPlayerConnection(CommonUtils.java:28)
[18:49:17 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.nms.packets.RawPacket.sendRawPacket(RawPacket.java:49)
[18:49:17 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.nms.packets.RawPacket.sendSuppressedPacket(RawPacket.java:38)
[18:49:17 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.nms.packets.PacketSend.animation(PacketSend.java:49)
[18:49:17 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.SleepHandler.reset(SleepHandler.java:54)
[18:49:17 WARN](java.lang.NullPointerException):        at me.mirreski.random.skript.features.packet.EffWakeUp.execute(EffWakeUp.java:30)
[18:49:17 WARN](java.lang.NullPointerException):        at ch.njol.skript.lang.Effect.run(Effect.java:50)
[18:49:17 WARN](java.lang.NullPointerException):        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63)
[18:49:17 WARN](java.lang.NullPointerException):        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91)
[18:49:17 WARN](java.lang.NullPointerException):        at ch.njol.skript.effects.Delay$1.run(Delay.java:85)
[18:49:17 WARN](java.lang.NullPointerException):        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[18:49:17 WARN](java.lang.NullPointerException):        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.ja
va:346)
[18:49:17 WARN](java.lang.NullPointerException):        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:862)
[18:49:17 WARN](java.lang.NullPointerException):        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
[18:49:17 WARN](java.lang.NullPointerException):        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
[18:49:17 WARN](java.lang.NullPointerException):        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
[18:49:17 WARN](java.lang.NullPointerException):        at java.lang.Thread.run(Unknown Source)

[18:49:17 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.reflection.helpers.HelperManager.getFromField(HelperManager.java:115
)
[18:49:17 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.reflection.helpers.ClassHelper.getFromField(ClassHelper.java:79)
[18:49:17 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.reflection.helpers.ObjectHelper.getFromField(ObjectHelper.java:34)
[18:49:17 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.CommonUtils.getPlayerConnection(CommonUtils.java:28)
[18:49:17 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.nms.packets.RawPacket.sendRawPacket(RawPacket.java:49)
[18:49:17 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.nms.packets.RawPacket.sendSuppressedPacket(RawPacket.java:38)
[18:49:17 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.nms.packets.PacketSend.animation(PacketSend.java:49)
[18:49:17 WARN](java.lang.NullPointerException):        at me.mirreski.random.utils.SleepHandler.reset(SleepHandler.java:54)
[18:49:17 WARN](java.lang.NullPointerException):        at me.mirreski.random.skript.features.packet.EffWakeUp.execute(EffWakeUp.java:30)
[18:49:17 WARN](java.lang.NullPointerException):        at ch.njol.skript.lang.Effect.run(Effect.java:50)
[18:49:17 WARN](java.lang.NullPointerException):        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63)
[18:49:17 WARN](java.lang.NullPointerException):        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91)
[18:49:17 WARN](java.lang.NullPointerException):        at ch.njol.skript.effects.Delay$1.run(Delay.java:85)
[18:49:17 WARN](java.lang.NullPointerException):        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[18:49:17 WARN](java.lang.NullPointerException):        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.ja
va:346)
[18:49:17 WARN](java.lang.NullPointerException):        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:862)
[18:49:17 WARN](java.lang.NullPointerException):        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
[18:49:17 WARN](java.lang.NullPointerException):        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
[18:49:17 WARN](java.lang.NullPointerException):        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
[18:49:17 WARN](java.lang.NullPointerException):        at java.lang.Thread.run(Unknown Source)

**Comment by Mirreski** [comment]
Yes I am aware that the sleep effect is broken/buggy. It has been that for quite a while.

It will be fixed when I release the remade RandomSK. And it will have the functional "Leave bed" button that I hadn't gotten to work before(It will probably be optional if you want it functional).

Thanks for reminding me. Adding it to my toodoo list so I don't forget it:)

**Comment by Twilight13** [comment]
On 4/16/2015 4:52 AM, Mirreski wrote:

> Yes I am aware that the sleep effect is broken/buggy. It has been that 
> for quite a while.
> 
> It will be fixed when I release the remade RandomSK. And it will have 
> the functional "Leave bed" button that I hadn't gotten to work 
> before(That will probably be optional if you want it functional).
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Mirreski/RandomSK/issues/18#issuecomment-93706818.

Thank you for your prompt reply, but most of all, thank you for your 
work on RandomSK. It opens up so many more possibilities, and has really 
enhanced my skripts. I very much appreciate it!

Twilight
